<?php
/** @var \Mirasvit\Credit\Block\Customer\Account $block */
/** @var \Magento\Framework\Escaper $escaper */
$balance = $block->getBalance();

$balanceAmount = $block->formatPrice($balance->getAmount(), $block->getStoreCurrencyCode(), $balance->getCurrencyCode());
$formId = 'form-validate';
?>

<div class="block credit__account-balance">
    <div class="block-title text-2xl m-4">
        <strong><?= __('Balance') ?></strong>
    </div>
    <div class="block-content m-4">
        <?= __('Current credit balance: <b>%1</b>', $balanceAmount) ?>
        <div class="credit__account-subscription" style="display: grid">
            <form class="form contact card lg:w-1/2 md:w-2/3"
                  style="float: left"
                  action="<?= $escaper->escapeUrl($block->getUrl('credit/account/subscribe')) ?>"
                  id="<?= $escaper->escapeHtmlAttr($formId) ?>"
                  method="post"
                  x-data="saveSubscription()"
                  @submit.prevent="submitForm()"
            >
                <div class="flex gap-2 flex-col">
                    <input
                        type='checkbox'
                        id="credit_subscription"
                        name="is_subscribed"
                        class="mr-2"
                        @click="creditSubscribtion"
                        <?= $balance->getIsSubscribed() ? 'checked' : '' ?>

                    <label for="credit_subscription">
                        <?= __('Subscribe to email notifications') ?>
                    </label>

                    &nbsp;&nbsp;<?= $block->getBlockHtml('formkey') ?>
                    <button id="subscribe_button" type="submit" class="btn btn-primary text-center justify-center" style="display: none;" >
                        <span><?= __('Save') ?></span>
                    </button>
                </div>
            </form>
        </div>

        <?php if ($block->hasSeveralBalances()): ?>
            <p>
                <?= __('* You also have credits in another currency') ?>
            </p>
        <?php endif; ?>
    </div>
</div>

<script>
    function creditSubscribtion() {
        var subscribeButton = document.getElementById('credit_subscription').checked;

        if (subscribeButton != !document.getElementById('credit_subscription').checked) {
            document.getElementById('subscribe_button').style.display = 'block';
        } else {
            document.getElementById('subscribe_button').style.display = 'none';
        }
    }

    function saveSubscription() {
        return {
            submitForm() {
                // Do not rename $form, the variable is expected to be declared in the recaptcha output
                const $form = document.querySelector('#<?= $escaper->escapeJs($formId) ?>');
                $form.submit();
            }
        }
    }
</script>
