<?php
//@codingStandardsIgnoreFile
/** @var \Mirasvit\Credit\Block\Customer\Account $block */

$balance = $block->getBalance();
$transactions = $block->getTransactionCollection();
?>

<div class="block">
    <div class="block-title text-2xl mb-6">
        <strong><?= __('Transactions History') ?></strong>
    </div>
    <div class="block-content">
        <?php if ($transactions->count()): ?>
            <div class="table-wrapper orders-recent">
                <table class="w-full sm:table-fixed lg:table-auto">
                    <thead>
                    <tr>
                        <th class="p-2 text-start"><?= __('Date') ?></th>
                        <th class="p-2 text-start"><?= __('Comment') ?></th>
                        <th class="p-2 text-start"><?= __('Action') ?></th>
                        <th class="p-2 text-start"><?= __('Amount') ?></th>
                        <th class="p-2 text-start"><?= __('Balance') ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $odd = 0 ?>
                    <?php foreach ($transactions as $transaction): ?>
                        <tr class="align-top even:bg-container-darker">
                            <td class="p-2 hidden lg:table-cell" data-th="<?= __('Date') ?>" nowrap>
                                <?= $block->escapeHtml($block->formatDate($transaction->getCreatedAt())) ?>
                            </td>
                            <td class="p-2 hidden lg:table-cell" data-th="<?= __('Comment') ?>"><?= $transaction->getFrontendMessage() ?></td>
                            <td class="p-2 hidden lg:table-cell" data-th="<?= __('Action') ?>"><?= $block->getAction($transaction) ?></td>
                            <td class="p-2 hidden lg:table-cell" data-th="<?= __('Amount') ?>">
                                <span style="color: <?= $transaction->getBalanceDelta() > 0 ? '#0a0' : '#f00' ?>">
                                    <?= $block->formatPrice($transaction->getBalanceDelta(), $transaction->getCurrencyCode()) ?>
                                </span>
                            </td>
                            <td class="last p-2 hidden lg:table-cell" data-th="<?= __('Balance') ?>">
                                <?= $block->formatPrice($transaction->getBalanceAmount(), $block->getStoreCurrencyCode(), $balance->getCurrencyCode()); ?>
                            </td>
                        </tr>
                    <?php endforeach ?>
                    </tbody>
                </table>
            </div>
        <?php else: ?>
            <div class="message info empty">
                <span><?= __('There have been no transactions made yet.') ?></span>
            </div>
        <?php endif ?>
    </div>
</div>
